[package]
name = "vsock"
version = "0.5.2"
authors = ["fsyncd", "rust-vsock"]
description = "Virtio socket support for Rust"
repository = "https://github.com/rust-vsock/vsock-rs"
homepage = "https://github.com/rust-vsock/vsock-rs"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
exclude = ["test_fixture"]

[dependencies]
rustix = { git = "https://github.com/forkgull/rustix", branch = "notgull/vsock", default-features = false, features = ["std", "net"] }

[dev-dependencies]
rand = "0.9.0"
sha2 = "0.10.8"
